### ISSUE TITLE
Can you merge the updates from the parent repository?

### ISSUE THREAD

**Issue by AlphaCreativeDev** [Telerik-Verified-Plugins/Badge#2]
We are having issues with this plugin on iOS 10 and see it hasn't been merged with the latest fixes from the parent repository in quite a while.  Can you please update it?

**Comment by EddyVerbruggen** [comment]
OK - please give version 0.8.1 a spin.

**Comment by AlphaCreativeDev** [comment]
That fixed the issue we were having.  We also had entered a ticket with Telerik.

**Comment by EddyVerbruggen** [comment]
OK, please close it or have it closed if you haven't done so yet. Thx!

**Comment by AlphaCreativeDev** [comment]
Done. Thank you!
